### ISSUE TITLE
Adding a Contributing.md File

### ISSUE THREAD

**Issue by Jazz-45** [iamkanhaiyakumar/ai-content-generator#1]

**Comment by iamkanhaiyakumar** [comment]
Go ahead @Jazz-45

**Comment by Jazz-45** [comment]
> Firstly you give the description of the issue after that you Go ahead @Jazz-45

Currently, our project lacks a CONTRIBUTING.md file that provides guidelines for contributors. This file is important to help ensure that contributions are consistent and meet the project's standards. By adding a CONTRIBUTING.md file, we can:

Clarify the Contribution Process: Provide clear steps for submitting issues and pull requests.
Code Style Guidelines: Set standards for coding style, formatting, and documentation.
Branching and Commit Message Conventions: Outline the rules for branch naming, commit messages, and PR creation.
Code of Conduct: Optionally include or link to the project's code of conduct.
Testing and Reviewing: Explain any required tests, CI pipelines, or review processes.
Tasks:

Draft the CONTRIBUTING.md file.
Include information on how to clone, test, and submit a PR.
Define coding standards and practices (e.g., language-specific guidelines).
Add sections for reporting issues and feature requests.
Optionally include guidelines on how to document changes and testing requirements.
Create a PR with the CONTRIBUTING.md file in the root of the repository.
Expected Outcome: Having this file will make it easier for new contributors to understand the process of contributing to the project and improve the quality and consistency of contributions.

**Comment by SaanyaGarg5** [comment]
You can assign me this task under gsssoc and hacktoberfest level 3 label.

**Comment by Jazz-45** [comment]
This task is already completed @SaanyaGarg5
