### ISSUE TITLE
Update readme.md file

### ISSUE THREAD

**Issue by jaidh01** [iamkanhaiyakumar/ai-content-generator#2]
I think some improvement can be done in the readme.md file, which can make it more attractive,
And I will also the live profile photos of the contributors.

**Comment by jaidh01** [comment]
Hi @iamkanhaiyakumar,
I request you to please add the `gssoc-extd` and `hacktoberfest` label to this issue.

Thank you for your time!

**Comment by jaidh01** [comment]
Hi @iamkanhaiyakumar,
I request you to please add the `gssoc-extd` and `hacktoberfest` label to this issue.

Thank you for your time!

**Comment by iamkanhaiyakumar** [comment]
Thank u for your contribution. Can you give star to  my  project.

**Comment by jaidh01** [comment]
> Thank u for your contribution. Can you give star to my project.

Thanks! Done. 🌟

**Comment by jaidh01** [comment]
Hi @iamkanhaiyakumar @sanjay-kv,
Just want to tell you that your repository doesn't have the `hacktoberfest` label, because of which it is not getting counted in Hacktoberfest.
