### ISSUE TITLE
[Feat] Updates in README.md

### ISSUE THREAD

**Issue by GauravKesh** [iamkanhaiyakumar/ai-content-generator#20]
### Description

In readme it's not mentioned how to setup database and clerk   and  it's might be difficult for the new  contributor to understand .

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by GauravKesh** [comment]
@iamkanhaiyakumar in readme .env.local section  and .env.example file i forgot to add 

NEXT_PUBLIC_GOOGLE_GEMINI_API_KEY = "YOUR-GOOGLE-GEMINI-API-KEY"

can you please modify the changes in both readme and .env.example file.
I'm sorry for inconvenience .

**Comment by devxMani** [comment]
@GauravKesh this error is coming whenever I am running this project can you tell me anything about this 
![image](https://github.com/user-attachments/assets/041c9ca6-6fe4-4c21-85d1-86872f7a6a31)

**Comment by GauravKesh** [comment]
@devxMani 
## Tailwind CSS Module Issue

### Possible Solutions

1. **Install Missing Tailwind CSS Module**  
   Run the following command to install Tailwind CSS along with its necessary dependencies:
   ```bash
   npm install -D tailwindcss postcss autoprefixer
   
   
 2. Also merge main in your branch if above doesn't works fine.Then it should start.
 
 
 ## Important to keep in mind
 - Please describe the issue little in depth like what you did, which file, or after which action  that you got this error so any person who know can easily help you.
