### ISSUE TITLE
[BUG] Dependency conflict

### ISSUE THREAD

**Issue by ShubhamKadam098** [iamkanhaiyakumar/ai-content-generator#24]
### Description

When attempting to install dependencies using npm install, I'm encountering a dependency conflict between @toast-ui/react-editor and React 18. The @toast-ui/react-editor package (version 3.2.3) requires React 17 as a peer dependency, but the project is using React 18.3.1.
I've tried running npm install without any flags, but it fails due to this conflict.

### Screenshots

Error:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @toast-ui/react-editor@3.2.3
npm ERR! Found: react@18.3.1
npm ERR! node_modules/react
npm ERR!   react@"^18" from the root project
npm ERR!   peer react@">=18 || >=19.0.0-beta" from @clerk/clerk-react@5.9.1
npm ERR!   node_modules/@clerk/clerk-react
npm ERR!     @clerk/clerk-react@"5.9.1" from @clerk/nextjs@5.6.0
npm ERR!     node_modules/@clerk/nextjs
npm ERR!       @clerk/nextjs@"^5.6.0" from the root project     
npm ERR!   12 more (@clerk/nextjs, @clerk/shared, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from @toast-ui/react-editor@3.2.3
npm ERR! node_modules/@toast-ui/react-editor
npm ERR!   @toast-ui/react-editor@"^3.2.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.1" from @toast-ui/react-editor@3.2.3
npm ERR!   node_modules/@toast-ui/react-editor
npm ERR!     @toast-ui/react-editor@"^3.2.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\Sahil\AppData\Local\npm-cache\_logs\2024-10-17T20_27_25_677Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\Sahil\AppData\Local\npm-cache\_logs\2024-10-17T20_27_25_677Z-debug-0.log

### Any additional information?

The project is using other packages that require React 18, such as @clerk/clerk-react and @clerk/nextjs, so downgrading React is not a viable option.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by GauravKesh** [comment]
@ShubhamKadam098 We'll look into the issue .Thank your for letting us know this.
