### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [iamkanhaiyakumar/ai-content-generator#25]
### Description

I want to add a page to showcase all the contributors of this website
@iamkanhaiyakumar can you assign me this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by GauravKesh** [comment]
@T-Rahul-prabhu-38 Any updates

**Comment by iamkanhaiyakumar** [comment]
Hey @T-Rahul-prabhu-38 any update

**Comment by 112201007** [comment]
I would like to work on this. Please assign this task to me.

**Comment by 112201007** [comment]
I added contributors page. I have tested it locally, and everything is working fine (visible in screenshots attached in PR). The page successfully fetches and displays contributor data from GitHub, including their avatars and profile links.

But when I try to submit the PR, I am encountering some issues. Could you please review my PR and let me know if there's anything I might have missed or any issues with the setup?
https://github.com/iamkanhaiyakumar/ai-content-generator/pull/83
