### ISSUE TITLE
Adding a Code of Conduct Page

### ISSUE THREAD

**Issue by jaidh01** [iamkanhaiyakumar/ai-content-generator#3]
To maintain a healthy and collaborative environment, I propose the addition of a Code of Conduct page in the repository. This page will outline the expected behavior, values, and guidelines for interactions among contributors. By defining clear standards, it will help prevent inappropriate behavior, promote inclusivity, and create a positive space for contributors of diverse backgrounds.

* Key elements include:

  1. Respectful communication
  2. Inclusive language
  3. Collaboration over competition
  4. Reporting and addressing issues

This will enhance community engagement and project development.

**Comment by jaidh01** [comment]
Hi @iamkanhaiyakumar,
I request you to please add the `gssoc-extd` and `hacktoberfest-accepted` label to this issue.

Thank you for your time!

**Comment by iamkanhaiyakumar** [comment]
Thank u for your contribution. Can you give star to  my  project.
