### ISSUE TITLE
[Feat] Add Mobile Sidebar

### ISSUE THREAD

**Issue by ShubhamKadam098** [iamkanhaiyakumar/ai-content-generator#30]
### Description

This PR adds a mobile-friendly sidebar using the Shadcn Sheet component to enhance the user experience on smaller screens. Additionally, layout improvements have been made to ensure seamless design and better responsiveness across all devices.

**Features:**
- Implemented mobile sidebar using Shadcn Sheet component for smooth transitions.
- Optimized layout structure for better alignment and user interaction.
- Ensured compatibility with existing styles and components.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by GauravKesh** [comment]
@ShubhamKadam098 You can start working on this issue
