### ISSUE TITLE
[Feat] Add a landing page

### ISSUE THREAD

**Issue by ShubhamKadam098** [iamkanhaiyakumar/ai-content-generator#31]
### Description

This PR introduces a new responsive landing page, designed to be fully compatible with all devices. The design has been attached for reference and adheres to modern UI/UX principles, ensuring a clean and engaging user experience.

**Key Features:**

Fully responsive landing page compatible across mobile, tablet, and desktop devices.
The page includes sections for introduction, features, and a call-to-action.
Optimized for fast loading and SEO-friendly structure.
Currently, the project does not have any landing page, so this will be a significant enhancement.

### **Desktop**
![image](https://github.com/user-attachments/assets/9e73b912-dbac-4d80-adbd-9007ea14a29a)

### **Mobile**
![image](https://github.com/user-attachments/assets/ed07c72a-9f3a-4031-8062-66f31927d38b)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

----
**Additional Note:**
The current content is placeholder text and will be updated later.

**Comment by GauravKesh** [comment]
@ShubhamKadam098 You can start working on it

**Comment by GauravKesh** [comment]
Hi @ShubhamKadam098 ,

For the middleware, please set it up so that unauthenticated users are redirected to the landing page, while logged-in users access the main app. Also, you'll need to update the public navigation bar to handle navigation accordingly. Once everything is working fine, please make a PR and include a demo video.

Let me know if you need any help with the implementation!

**Comment by ShubhamKadam098** [comment]
Hi @GauravKesh ,

Sure No problem. I’ll implement these changes, no worries. I’ve already completed the landing page updates, so I’ll create a PR for that by the end of today. For the auth changes, should I create a new issue outlining all the changes and implementations, or should I include them in this one?

**Comment by GauravKesh** [comment]
@ShubhamKadam098 No need to make a separate PR; it’ll be easier for you to implement everything together.

**Comment by ShubhamKadam098** [comment]
Hey @GauravKesh ,

Apologies for the late reply! I’m encountering some issues during the build process, specifically with three errors in the `Button`, `Layout`, and `Output` components.

- **Output.tsx**  
  ![image](https://github.com/user-attachments/assets/274a31e4-d115-4616-927e-ad894e70012e)


- **Layout.tsx**  
  ![image](https://github.com/user-attachments/assets/beeba561-6cfe-4c4f-9efc-294e0e89f781)

- **Button.tsx**  
  ![image](https://github.com/user-attachments/assets/bcfd6637-fa2a-4d5c-b5e9-4ad8d6fc5c72)

Aside from that, I’ve completed the landing page. Here’s the demo video:

Desktop View.

https://github.com/user-attachments/assets/84f16ba2-ffb5-4028-a953-0cdcdbe7e733



Mobile View

https://github.com/user-attachments/assets/61cacc51-8435-4396-8d47-0cae652bcef8




Could you please take a look at these issues and advise on how I should proceed? Also, let me know if there are any changes needed for the landing page.

Thanks!

**Comment by GauravKesh** [comment]
@ShubhamKadam098 I didn't what's the issue

**Comment by GauravKesh** [comment]
@ShubhamKadam098 Hi i'll look into the issue


is it working fine  other than build command ?

**Comment by ShubhamKadam098** [comment]
Hey @GauravKesh ,

Yes, aside from these three issues, everything else is working fine.

**Comment by GauravKesh** [comment]
@ShubhamKadam098 The errors are related to `"type error"` also for 1st image try to update the package.
If it's working normally it's fine for now. We can merge it .Give a try and fix this by looking into the type chnages.

**Comment by ShubhamKadam098** [comment]
Hey @GauravKesh  ,

Could you please add the Hacktoberfest accepted tag? For some reason, this PR isn’t getting recognized for Hacktoberfest.

Thanks for your assistance!
