### ISSUE TITLE
Deployment on Vercel

### ISSUE THREAD

**Issue by Ahsankhalid618** [iamkanhaiyakumar/ai-content-generator#5]
To enhance the deployment process and improve accessibility, I propose we deploy the project on Vercel. It offers automatic deployments, preview URLs for pull requests, and efficient scaling, which can significantly streamline the workflow.

**Key benefits include:**

- Automatic Deployments: Reduces manual effort and errors.

- Preview Links: Allows for review of changes before merging.

- Scalability: Easily handles increased traffic as we grow.

Implementing this will improve collaboration and make our project more robust.

Kindly assign this issue to me and add the Gssoc, Hacktoberfest, and level2 labels. Thanks

**Comment by dev129** [comment]
I think problem might be that the variables might not be declared in the projects, you can go in sttings and resolve that

**Comment by Ahsankhalid618** [comment]
> I think problem might be that the variables might not be declared in the projects, you can go in sttings and resolve that 
> 
> 

Environment variables are declared, but vercel will only deploy when the original owner of the repository pushes the code to vercel or accepts the PR to vercel,

**Comment by dev129** [comment]
Even i think the same , and the dependencis have not been specified, the running method is also not popular

**Comment by Raj100** [comment]
I will do it Assign it to me! Thank You!😊

**Comment by GauravKesh** [comment]
@iamkanhaiyakumar is this issue fixed ?

**Comment by iamkanhaiyakumar** [comment]
No, this cause I don't close this issue

**Comment by iamkanhaiyakumar** [comment]
Hey @Raj100 any update??
