### ISSUE TITLE
🚀 Automate Connections with GitHub Actions!

### ISSUE THREAD

**Issue by amiya-cyber** [iamkanhaiyakumar/ai-content-generator#53]
We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label
@iamkanhaiyakumar

**Comment by amiya-cyber** [comment]
hello @iamkanhaiyakumar i think it deserves level3 label can you remove level1 and give level3

**Comment by iamkanhaiyakumar** [comment]
> hello @iamkanhaiyakumar i think it deserves level3 label can you remove level1 and give level3

I think u only work on few line of code

**Comment by amiya-cyber** [comment]
yeah but still i think you can give atleast level2 label
