### ISSUE TITLE
[Feat]-Creating Responsive Navbar

### ISSUE THREAD

**Issue by dev129** [iamkanhaiyakumar/ai-content-generator#55]
### Issue: Design and Implement Navbar for AI Content Generator

Hi @iamkanhaiyakumar,

---

**Objective:**
Create a responsive and intuitive navigation bar for the AI Content Generator that provides easy access to the main sections of the site, improves user experience, and aligns with the overall design of the landing page.

---

**Key Responsibilities:**

1. **Design Layout**:
   - Create a wireframe or design draft for the navbar, ensuring it aligns with modern UI/UX standards and the visual style of the landing page.
   - The navbar should include links to key sections, such as Home, Features, About, and Contact, and a call-to-action button if necessary.

2. **Implement Features**:
   - Develop the navbar using **Next.js** and **TypeScript** for maintainability and scalability.
   - Ensure the navbar is fully responsive across devices with CSS frameworks or custom styling as appropriate.
   - Add interactive elements such as smooth scrolling to anchor links, hover effects, and a mobile-friendly toggle for smaller screens.

3. **SEO and Accessibility**:
   - Use semantic HTML and appropriate ARIA attributes to ensure the navbar is accessible for all users.
   - Ensure the navbar structure contributes positively to the page’s SEO by providing clear navigation paths.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by GauravKesh** [comment]
@dev129  "Thanks for identifying the issue! Currently, someone is working on the navbar, so let’s wait until those changes are merged. Once that’s complete, you can start working on your updates."

**Comment by iamkanhaiyakumar** [comment]
Hey @GauravKesh Let him also work, it would be best if we merge it because it took a lot of time and there is very little time left for the program to end

**Comment by GauravKesh** [comment]
@iamkanhaiyakumar yeah sure

**Comment by dev129** [comment]
Hi @GauravKesh @iamkanhaiyakumar , this is some modification applied on Navbar.
![image](https://github.com/user-attachments/assets/ebd49d52-f814-4391-bb84-574a3de8d6d3)

**Comment by dev129** [comment]
@GauravKesh , just tell me a brief about what go to dashboard shall give , if you have an image it would be better.

**Comment by GauravKesh** [comment]
@dev129 Yeah similar to that

**Comment by dev129** [comment]
@GauravKesh , some names can be Spark Reality, Build Dream, Start Creating, Idea to Impact, Make Real.

**Comment by GauravKesh** [comment]
@dev129 That's great suggestion But what i'll suggest let it be  just "DASHBOARD" which will be easier to understand by other people.
