### ISSUE TITLE
[Feat]-creating error 404 page

### ISSUE THREAD

**Issue by dev129** [iamkanhaiyakumar/ai-content-generator#56]
### Issue: Design and Implement 404 Error Page for AI Content Generator

Hi @iamkanhaiyakumar,

---

**Objective:**
Develop a custom 404 Error page for the AI Content Generator that clearly indicates when a user navigates to a non-existent page. The page should align with the overall design style and provide users with options to navigate back to the main areas of the site.

---

**Key Responsibilities:**

1. **Design Layout**:
   - Create a wireframe or mockup for the 404 page that is visually engaging and user-friendly.
   - The layout should include a message like "Page Not Found," a call-to-action button to return to the homepage, and any other elements that improve user experience, such as links to the Help section or a Search bar.

2. **Implement Features**:
   - Build the 404 page using **Next.js** and **TypeScript** for consistency and maintainability.
   - Ensure responsive design, so the page displays well on both desktop and mobile devices.
   - Add interactive animations or illustrations to make the page feel polished and engaging.

3. **SEO and Accessibility**:
   - Include clear metadata that marks the page as a 404 error for SEO purposes.
   - Ensure the page is accessible with screen readers and has appropriate ARIA labels where needed.

---

**Skills Needed**:
- Experience with responsive UI design and accessibility standards.
- Knowledge of error handling and SEO best practices for 404 pages.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by dev129** [comment]
Hi @iamkanhaiyakumar , i have designed the error page , please let me know your thoughts on this design.

**Comment by dev129** [comment]
Hi @iamkanhaiyakumar , shall I start designing it ?

**Comment by GauravKesh** [comment]
@dev129 The design looks great! It matches the theme and the app really well, making everything look nice together.

**Comment by dev129** [comment]
@GauravKesh , can i launch all 3 PR as they get completed , since I shall be travelling tomorrow , so @iamkanhaiyakumar whenever he checks you don't have to wait for PR and then merge it , besides it festive time also , what say ?

**Comment by GauravKesh** [comment]
@dev129 yeah sure
