### ISSUE TITLE
[Feat] Review Section Design at the landing page 

### ISSUE THREAD

**Issue by dev129** [iamkanhaiyakumar/ai-content-generator#70]
### Issue: Creation of a Review Section for "AI Content Generator" Website

Hi @iamkanhaiyakumar @GauravKesh 

#### **Project Overview**
The "AI Content Generator" website is a platform built to deliver AI-powered content generation tools tailored to various professional needs. This site leverages modern development frameworks to ensure efficient, scalable content workflows, ultimately enhancing productivity across diverse user groups. The website caters to multiple user personas by providing specialized toolsets, each designed to streamline specific tasks for coders, content creators, and social media influencers.

#### **Objective**
To develop a comprehensive review section for "AI Content Generator" that captures user feedback on the various AI tools available. The review section will allow users to share insights, rate features, and provide suggestions based on their experiences. This addition will not only foster community engagement but also provide valuable feedback for iterative improvements.

#### **Targeted Tools for Review**
The review section should allow users to provide feedback on specific tools within the platform, including but not limited to:

1. **For Coders**:
   - **Write Code**: AI-assisted code generation with support for multiple programming languages and styles.
   - **Debug**: Automated debugging tool to identify and suggest solutions for common coding issues.
   - **Run Test**: Tool to execute test cases and provide feedback on code quality, performance, and optimization.

2. **For YouTubers**:
   - **YouTube SEO**: Optimizes video metadata for better search visibility and engagement on YouTube.
   - **Script Writer**: Assists in generating and structuring engaging video scripts based on topic input.
   - **Hashtag Generator**: Suggests relevant hashtags to boost video discoverability and reach.

3. **For Instagram**:
   - **Post Caption Creator**: Generates captions tailored to the post’s theme and tone.
   - **Hashtag Generator**: Identifies trending hashtags relevant to the post to enhance engagement.
- **Post Idea Generator**:Generate ideas which creators can use for their own purpose.

#### **Proposed Structure for the Review Section**
The review section should be structured to capture user feedback in a way that is both organized and actionable:

**Ratings and Reviews**:
   - **Rating**: A star-based or numerical rating system (e.g., 1-5 stars).
   - **Commentary**: Text boxes allowing users to elaborate on their experience with each tool.

#### **Benefits of the Review Section**
- **User Engagement**: Encourages active participation, fostering a sense of community among users.
- **Product Improvement**: Collects valuable feedback for developers to enhance tools based on real user input.
- **Transparency and Trust**: Demonstrates a commitment to user satisfaction and continuous improvement.
  
This review section will not only enhance user engagement but also provide a roadmap for the continuous enhancement of the AI Content Generator platform.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by dev129** [comment]
Hi @GauravKesh , I just completed the design let me know what you think about it 
![image](https://github.com/user-attachments/assets/f2e8c4d1-bf11-4ad0-888f-244e1434ad23)

**Comment by GauravKesh** [comment]
@dev129 It's looking nice but need to add relevant data there. and do you have different idea also is it reponsive for all devices

**Comment by dev129** [comment]
@GauravKesh 
Responsiveness is still to be tested, its a matter of few minute and as for ideas what we can do is tag give somewhat famous faceless YT creators who use AI, some software engineers will in MAANG, I can also add an auto play button between left and right button which plays comment automatically

**Comment by GauravKesh** [comment]
Sure thing, @dev129 ! Instead of tagging famous YouTube creators without their okay, we can use titles like 'AI Enthusiast' or 'Tech Expert.' We can also highlight comments from real users and smaller creators to make the content more engaging and fun!

**Comment by dev129** [comment]
Hi @GauravKesh , here is the updated version with changes you suggested, any more changes you wanna see 
https://github.com/user-attachments/assets/08816e2a-08b0-40b2-b7a1-518d2ee1b80c

**Comment by dev129** [comment]
Hi @GauravKesh @iamkanhaiyakumar do you like the design ?

**Comment by GauravKesh** [comment]
@dev129 It's looking good. Just make the buttons round

**Comment by dev129** [comment]
Very well @GauravKesh , you please assign the level label.

**Comment by dev129** [comment]
Hi @GauravKesh @iamkanhaiyakumar , this is the final design , I hope you will like it.

https://github.com/user-attachments/assets/4da4aa02-da5e-4b88-a311-374b2001367e

I have made the button round, setup autoplay, applied images.

**Comment by dev129** [comment]
Hi @GauravKesh , shall I launch the PR ?

**Comment by GauravKesh** [comment]
@dev129 yeah you can make PR
