### ISSUE TITLE
[Feat]Adde the security

### ISSUE THREAD

**Issue by Dipanita45** [iamkanhaiyakumar/ai-content-generator#74]
### Description

Security of the website

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by GauravKesh** [comment]
@Dipanita45 Please explain in detail

**Comment by GauravKesh** [comment]
@Dipanita45 Please explain the issue in  in detail.

**Comment by Dipanita45** [comment]
Want to add security to protect the website for the harms

**Comment by GauravKesh** [comment]
@Dipanita45 I got your point what kind of security , you need to explain what's the main context . Please do explain.
Authentication or protection form DDOS attack.

**Comment by Dipanita45** [comment]
Please merge my pull request
